# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='role_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amer.Stats'),
        ),
    ]
