# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amer', '0002_auto_20160508_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='role_stats',
        ),
        migrations.AddField(
            model_name='character',
            name='power',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='speed',
            field=models.IntegerField(default=2),
        ),
        migrations.DeleteModel(
            name='Character_Stats',
        ),
    ]
