# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amer', '0003_auto_20160508_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='capacity_height',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='character',
            name='capacity_width',
            field=models.IntegerField(default=4),
        ),
    ]
